ALTER TABLE "feature_flag_rules" DROP CONSTRAINT "feature_flag_rules_stage_valid";--> statement-breakpoint
ALTER TABLE "feature_flag_rules" ADD COLUMN "client_os" jsonb;--> statement-breakpoint
ALTER TABLE "feature_flag_rules" ADD COLUMN "min_client_build" integer;--> statement-breakpoint
ALTER TABLE "feature_flag_rules" ADD COLUMN "client_build_types" jsonb;--> statement-breakpoint
ALTER TABLE "feature_flag_rules" ADD CONSTRAINT "feature_flag_rules_client_fields_scoped" CHECK ("feature_flag_rules"."stage" = 'client' OR ("feature_flag_rules"."client_os" IS NULL AND "feature_flag_rules"."min_client_build" IS NULL AND "feature_flag_rules"."client_build_types" IS NULL));--> statement-breakpoint
ALTER TABLE "feature_flag_rules" ADD CONSTRAINT "feature_flag_rules_client_shape_valid" CHECK ("feature_flag_rules"."stage" <> 'client' OR ("feature_flag_rules"."percentage_basis_points" IS NULL AND "feature_flag_rules"."variant" IS NULL AND jsonb_array_length("feature_flag_rules"."values") > 0 AND ("feature_flag_rules"."client_os" IS NOT NULL OR "feature_flag_rules"."min_client_build" IS NOT NULL OR "feature_flag_rules"."client_build_types" IS NOT NULL)));--> statement-breakpoint
ALTER TABLE "feature_flag_rules" ADD CONSTRAINT "feature_flag_rules_client_os_valid" CHECK ("feature_flag_rules"."client_os" IS NULL OR (jsonb_typeof("feature_flag_rules"."client_os") = 'array' AND jsonb_array_length("feature_flag_rules"."client_os") > 0 AND "feature_flag_rules"."client_os" <@ '["android","ios","ohos"]'::jsonb));--> statement-breakpoint
ALTER TABLE "feature_flag_rules" ADD CONSTRAINT "feature_flag_rules_client_build_types_valid" CHECK ("feature_flag_rules"."client_build_types" IS NULL OR (jsonb_typeof("feature_flag_rules"."client_build_types") = 'array' AND jsonb_array_length("feature_flag_rules"."client_build_types") > 0 AND "feature_flag_rules"."client_build_types" <@ '["release","alpha","debug"]'::jsonb));--> statement-breakpoint
ALTER TABLE "feature_flag_rules" ADD CONSTRAINT "feature_flag_rules_min_client_build_valid" CHECK ("feature_flag_rules"."min_client_build" IS NULL OR "feature_flag_rules"."min_client_build" >= 0);--> statement-breakpoint
ALTER TABLE "feature_flag_rules" ADD CONSTRAINT "feature_flag_rules_stage_valid" CHECK ("feature_flag_rules"."stage" IN ('user', 'platform', 'client', 'server', 'audience', 'lab', 'plan', 'percentage'));