import type { ApiProxyDiagnostics, ApiResponse } from "../client";
import { CliError, type CliErrorCode } from "./errors";

type ApiFailure = Pick<ApiResponse<unknown>, "status" | "errorCode" | "suggestedNextAction" | "proxy"> & {
  error?: string | null;
};

export function apiFailureError(
  response: ApiFailure,
  fallbackCode: string,
  options: {
    server5xxCode?: CliErrorCode;
    suggestedNextAction?: string;
  } = {},
): CliError {
  const proxyFailure = response.status >= 500 && response.errorCode === "agent_proxy_failed";
  const code = response.status >= 500
    ? proxyFailure
      ? "PROXY_5XX"
      : (response.errorCode as CliErrorCode | undefined) ?? options.server5xxCode ?? "SERVER_5XX"
    : (response.errorCode as CliErrorCode | undefined) ?? fallbackCode as CliErrorCode;
  return new CliError({
    code,
    message: response.error ?? `HTTP ${response.status}`,
    suggestedNextAction: options.suggestedNextAction
      ?? response.suggestedNextAction
      ?? (proxyFailure ? proxyFailureNextAction(response.proxy) : undefined),
    ...proxyCliErrorOptions(response.proxy),
  });
}

/**
 * Default `Next action` for a 5xx envelope generated by the local daemon proxy
 * (`code: agent_proxy_failed`), chosen by the proxy's own `failure_class`.
 *
 * The daemon writes a transport log line and span for every proxy failure, but
 * what that record contains differs by class:
 *
 * - `upstream_http_response`: the upstream answered with a 5xx. The proxy reads
 *   the upstream body and discards it; its log and span keep only the status
 *   and failure codes. The transport log therefore cannot show what the server
 *   said. The correlation id is minted by the daemon and returned downstream
 *   only; the server saw the daemon's `traceparent`, so the server-side join
 *   key is the trace id carried by the daemon proxy span that records this
 *   correlation id.
 * - transport classes (`pre_response_transport`, `mid_response_transport`) and
 *   unknown/missing diagnostics: the proxy log records the underlying transport
 *   error and its cause, which the receipt does not carry, so inspecting it is
 *   the right first step.
 */
export function proxyFailureNextAction(proxy: ApiProxyDiagnostics | null | undefined): string {
  if (proxy?.failureClass === "upstream_http_response") {
    const status = typeof proxy.upstreamStatus === "number" ? `HTTP ${proxy.upstreamStatus}` : "a 5xx";
    return `The local daemon proxy relayed ${status} from upstream and discarded the upstream response body; `
      + "its transport log records only the status and failure class. The correlation id is local to this daemon: "
      + "find the daemon proxy span that carries it, take that span's trace id, and read the server-side trace "
      + "for the request before attributing this to the server; if no such trace is found, the attribution stays unknown.";
  }
  return "This 5xx was generated by the local daemon proxy; use the correlation id to inspect daemon proxy transport logs before attributing it to the server.";
}

export function proxyCliErrorOptions(proxy: ApiProxyDiagnostics | null | undefined): {
  layer?: string;
  correlationId?: string;
  proxyFailureClass?: string;
  proxyCauseCode?: string;
  proxyRouteFamily?: string;
  proxyUpstreamLayer?: string;
  proxyUpstreamStatus?: number;
  proxyResponseStarted?: boolean | null;
  proxyResponseComplete?: boolean | null;
} {
  if (!proxy) return {};
  return {
    layer: proxy.layer ?? undefined,
    correlationId: proxy.correlationId ?? undefined,
    proxyFailureClass: proxy.failureClass ?? undefined,
    proxyCauseCode: proxy.causeCode ?? undefined,
    proxyRouteFamily: proxy.routeFamily ?? undefined,
    proxyUpstreamLayer: proxy.upstreamLayer ?? undefined,
    proxyUpstreamStatus: proxy.upstreamStatus ?? undefined,
    proxyResponseStarted: proxy.responseStarted ?? undefined,
    proxyResponseComplete: proxy.responseComplete ?? undefined,
  };
}
