// task #333: the default `Next action` for a daemon-proxy 5xx must follow the
// proxy's failure_class. For upstream_http_response the daemon discards the
// upstream body and logs only status + codes, so pointing the reader at the
// daemon proxy transport log cannot answer "what did the server say".
import assert from "node:assert/strict";

import { apiFailureError, proxyFailureNextAction } from "./apiFailure";

const TRANSPORT_LOG_HINT =
  "This 5xx was generated by the local daemon proxy; use the correlation id to inspect daemon proxy transport logs before attributing it to the server.";

function proxyFailure(proxy: Parameters<typeof proxyFailureNextAction>[0]) {
  return {
    status: 503,
    error: "upstream HTTP response failed",
    errorCode: "agent_proxy_failed",
    suggestedNextAction: null,
    proxy,
  };
}

test("upstream_http_response: next action sends the reader to the server side, not the proxy transport log", () => {
  const err = apiFailureError(
    proxyFailure({
      layer: "local_daemon_proxy",
      correlationId: "259de033fbf60c5c",
      failureClass: "upstream_http_response",
      causeCode: "HTTP_503",
      routeFamily: "agent-api/events",
      upstreamLayer: "http_status",
      upstreamStatus: 503,
      responseStarted: true,
      responseComplete: true,
    }),
    "SEARCH_FAILED",
  );
  assert.equal(err.code, "PROXY_5XX");
  const next = err.suggestedNextAction ?? "";
  assert.match(next, /HTTP 503/);
  assert.match(next, /discarded the upstream response body/);
  assert.match(next, /correlation id is local to this daemon/);
  assert.match(next, /trace id/);
  assert.match(next, /server-side trace/);
  assert.match(next, /attribution stays unknown/);
  assert.doesNotMatch(next, /inspect daemon proxy transport logs/);
  // The correlation id is never sent upstream (the proxy forwards traceparent),
  // so the copy must not present it as a server-side lookup key.
  assert.doesNotMatch(next, /correlation id against the server/);
});

test("pre_response_transport: next action keeps the proxy transport log hint (that log carries the transport cause)", () => {
  const err = apiFailureError(
    proxyFailure({
      layer: "local_daemon_proxy",
      correlationId: "eb15805d2c86f215",
      failureClass: "pre_response_transport",
      causeCode: "ETIMEDOUT",
      routeFamily: "agent-api/events",
      responseStarted: false,
      responseComplete: false,
    }),
    "READ_FAILED",
  );
  assert.equal(err.code, "PROXY_5XX");
  assert.equal(err.suggestedNextAction, TRANSPORT_LOG_HINT);
});

test("mid_response_transport and missing diagnostics fall back to the transport log hint", () => {
  assert.equal(proxyFailureNextAction({ failureClass: "mid_response_transport" }), TRANSPORT_LOG_HINT);
  assert.equal(proxyFailureNextAction(null), TRANSPORT_LOG_HINT);
  assert.equal(proxyFailureNextAction(undefined), TRANSPORT_LOG_HINT);
});

test("upstream_http_response without a numeric upstream status still names the discarded body", () => {
  const next = proxyFailureNextAction({ failureClass: "upstream_http_response" });
  assert.match(next, /relayed a 5xx from upstream/);
  assert.match(next, /discarded the upstream response body/);
});

test("an explicit caller or upstream next action still wins over the default", () => {
  const upstream = apiFailureError(
    { ...proxyFailure({ failureClass: "upstream_http_response", upstreamStatus: 503 }), suggestedNextAction: "Retry after the server reports healthy." },
    "X",
  );
  assert.equal(upstream.suggestedNextAction, "Retry after the server reports healthy.");
  const caller = apiFailureError(
    proxyFailure({ failureClass: "upstream_http_response", upstreamStatus: 503 }),
    "X",
    { suggestedNextAction: "Caller-specific guidance." },
  );
  assert.equal(caller.suggestedNextAction, "Caller-specific guidance.");
});

test("non-proxy 5xx gets no default next action", () => {
  const err = apiFailureError({ status: 502, error: "bad gateway", errorCode: null, suggestedNextAction: null, proxy: null }, "X");
  assert.equal(err.code, "SERVER_5XX");
  assert.equal(err.suggestedNextAction, undefined);
});
