import assert from "node:assert/strict";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";

const testsRoot = import.meta.dirname;
const baselinePath = resolve(testsRoot, "helpers/assertionNullCompareGuard.baseline.json");

/**
 * DOM-node-compare hazard guard (task #627, reported by @Josh 2026-09-22;
 * widened from null-only to any DOM-node first argument in the D-class
 * follow-up after PR #8115).
 *
 * `assert.equal(<live DOM node>, …)` crashes the vitest worker when it
 * fails: the node becomes the `actual` value and node:assert walks the
 * whole React fiber graph hanging off it to build the diff — small trees
 * spam tens of KB, large trees kill the worker before anything is reported
 * ("Worker exited unexpectedly", tests 0ms, no assertion info). The boolean
 * form `assert.ok(screen.queryBy… === null)` fails readably and is identical
 * when green. Root fixes at the setup layer are proven impossible (node:assert
 * bypasses util.inspect.custom when building the diff — Bugen's experiment,
 * Josh's plain-object repro), so the durable control is a ratchet: no new
 * offender, no growth in existing files.
 *
 * Rule (single counter, single baseline): the FIRST argument of
 * assert.equal/strictEqual/deepEqual/deepStrictEqual matching a statically
 * recognizable DOM-node expression is an offender — no matter what the
 * second argument is. Comparing a node against a non-null value serializes
 * DOM on failure exactly the same way (Josh's 205s crash on
 * `panel.lastElementChild`, and `document.activeElement` repros), so the
 * right side is irrelevant.
 *
 * First-argument shapes covered (property chains like
 * `dom.window.document.querySelector` included):
 * - `screen.queryBy…` / `within(…).queryBy…` query calls
 * - `el.querySelector(All)(…)` and `el.closest(…)`
 * - named element properties: `document.activeElement`, and
 *   `el.firstElementChild / lastElementChild / parentElement /
 *   nextElementSibling / previousElementSibling`
 *
 * Known imprecision (both directions deliberate):
 * - Call arguments are matched up to their first `)`, so a query whose own
 *   argument contains a `)` (e.g. a regex literal with a capture group) is
 *   under-matched and can evade. Better miss an exotic case than crash on it.
 * - A node stored in a bare variable first (`const el = …; assert.equal(el, x)`)
 *   is statically undecidable and stays out of scope — that shape is handled
 *   by helper convention (e.g. an assertActiveElement-style helper that never
 *   hands the node to node:assert), not by this regex.
 * - `.length` / `.size` compares on query results are NUMBERS, not nodes, and
 *   are correctly NOT matched (the first-arg anchor ends at the query call).
 *
 * History note: the #8115 (v2) version of this rule interpolated the
 * first-arg alternation into the assert pattern WITHOUT a surrounding group,
 * so regex `|` split the whole expression — the query* family matched with no
 * right-side requirement at all, and the querySelector family matched with no
 * assert.( anchor. The v2 baseline was generated by that leaky rule; this
 * version groups the alternation, so the baseline composition legitimately
 * changes (drops numeric `.length` compares and non-assert leaked matches,
 * adds the activeElement/closest/element-property families and chained
 * prefixes like `dom.window.document.querySelector`).
 */
const DOM_NODE_FIRST_ARG = [
  String.raw`(?:screen\.|within\([^)]*\)\.)?query(?:By|AllBy)\w*\([^)]*\)`,
  String.raw`(?:[\w$]+\.)+querySelector(?:All)?\([^)]*\)`,
  String.raw`(?:[\w$]+\.)+closest\([^)]*\)`,
  String.raw`(?:[\w$]+\.)+(?:activeElement|firstElementChild|lastElementChild|parentElement|nextElementSibling|previousElementSibling)\b`,
].join("|");
const OFFENDER = new RegExp(
  `assert\\.(?:deepStrictEqual|deepEqual|strictEqual|equal)\\(\\s*(?:${DOM_NODE_FIRST_ARG})\\s*,`,
  "g",
);

function walkTests(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (entry === "node_modules" || entry.startsWith(".")) continue;
    try {
      const stat = statSync(full);
      if (stat.isDirectory()) {
        walkTests(full, out);
      } else if (entry.endsWith(".test.ts") || entry.endsWith(".test.tsx")) {
        out.push(full);
      }
    } catch (error) {
      // Only genuinely-unreadable entries are skipped — anything else (typos,
      // missing imports, permission surprises) must fail loudly, not silently
      // pass as an empty walk (the shape that made v1 of this guard inert).
      const code = (error as NodeJS.ErrnoException).code;
      if (code !== "ENOENT" && code !== "ELOOP") throw error;
    }
  }
  return out;
}

function countOffenders(path: string): number {
  const raw = readFileSync(path, "utf8")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/[^\n]*/g, "");
  return Array.from(raw.matchAll(OFFENDER)).length;
}

test("assertions handing a live DOM node to node:assert do not grow", () => {
  const current = new Map<string, number>();
  for (const file of walkTests(testsRoot)) {
    if (file.endsWith("assertionNullCompareGuard.test.ts")) continue;
    const count = countOffenders(file);
    if (count > 0) current.set(relative(testsRoot, file), count);
  }

  if (process.env.UPDATE_NULL_COMPARE_GUARD_BASELINE === "1") {
    // Regeneration floor (@Josh): an empty walk is always a bug (e.g. the
    // missing-import crash above), never a true state of this repo. Refuse to
    // overwrite the baseline with nothing instead of ratcheting it to zero.
    if (current.size === 0) {
      assert.fail(
        "guard found zero offenders — this can only be a broken scan (missing import, wrong root, silent catch). Refusing to write an empty baseline.",
      );
    }
    writeFileSync(
      baselinePath,
      `${JSON.stringify(Object.fromEntries([...current].sort()), null, 2)}\n`,
    );
    return;
  }

  const baseline: Record<string, number> = JSON.parse(readFileSync(baselinePath, "utf8"));
  const failures: string[] = [];
  for (const [file, count] of current) {
    const allowed = baseline[file] ?? 0;
    if (count > allowed) {
      failures.push(`${file}: ${count} (baseline ${allowed})`);
    }
  }
  for (const file of Object.keys(baseline)) {
    const count = current.get(file) ?? 0;
    if (count < baseline[file]) {
      failures.push(`${file}: ${count} (baseline ${baseline[file]} — improved; regenerate the baseline)`);
    }
  }

  assert.deepEqual(
    failures,
    [],
    "assertions with a live DOM node as first argument changed. Use the boolean form " +
      "`assert.ok(x === null)` / `assert.ok(a === b)` instead of `assert.equal(<DOM node>, …)` " +
      "(the latter crashes the worker on failure, whatever the right side is; see task #627). " +
      "If you genuinely reduced the count, regenerate: UPDATE_NULL_COMPARE_GUARD_BASELINE=1 " +
      "pnpm --filter @botiverse/raft-web test -- tests/assertionNullCompareGuard.test.ts\n" +
      failures.join("\n"),
  );
});
