// Task #91 route authority classification: every mutating route registered by createApp(), exactly once.
// Enforced by routeAuthorityClassification.structure.test.ts from runtime route registration.
//
// Buckets:
//   pure                — pure DB authority write, fenced by the actor membership fence in #91a
//   cat1                — route-level authority DB write fenced in #91a; any runtime effect stays open in #93 line A
//   cat2                — migration admission and effect both not linearized; #93 line C
//   cat3                — no route-level authority DB write; authority check → dispatch/effect chain open in #93 line A
//   lineG               — capability-only create; removal/demotion race is #93 line G
//   readState93         — human acting on an Agent's read state; admission and effect open in #93 line B
//   authorityTransition — the member removal / role change that fenced writes linearize against
//   channelLane         — channel-scoped authority with its own channel row locks
//   integrationLane     — external-auth routes: confirmed races fixed by #proj-backend-general #165, the rest audited by #167
//   providerConnectionResidual — provider-connection routes (manageExternalAuth; credentials/rotate under rotateServerSecrets); fix #proj-backend-general #165 (unified), audit #167, owner Ark
//   nonHuman            — caller is not a human session (agent, Computer, machine key, OAuth client, webhook)
//   notAgentMachine     — not membership or relationship authority over an Agent / Machine / Computer

export type RouteAuthorityBucket =
  | "authorityTransition"
  | "cat1"
  | "cat2"
  | "cat3"
  | "channelLane"
  | "integrationLane"
  | "lineG"
  | "nonHuman"
  | "notAgentMachine"
  | "providerConnectionResidual"
  | "pure"
  | "readState93";

export type RouteClassification = { route: string; bucket: RouteAuthorityBucket; reason: string };

/** The adjudicated #91a / #93 lists (#wg-rbac:c18cdc5f). Changing one of these counts is a scope decision. */
export const PINNED_BUCKET_COUNTS: Readonly<Record<string, number>> = {
  // +1: POST /api/agents/:id/hosted-runtime/retry (fenced editAgents/creator provisioning-row write).
  pure: 9,
  // Retired POST /api/wiki/setup (cat1) and POST /api/wiki/refresh (cat3).
  cat1: 10,
  cat2: 3,
  // +3: POST/DELETE /api/agents/:id/connections/:provider and POST …/confirm (editAgents or creator, never
  // guest; no route-level DB write besides the audit row; the effect is a provider call).
  // +2: PUT /api/agents/:id/connections/:provider and DELETE …/connectors/:connectorId (same, plus the
  // connector's creator or owner/admin).
  cat3: 14,
  lineG: 3,
  readState93: 1,
};

export const ROUTE_AUTHORITY_CLASSIFICATION: readonly RouteClassification[] = [
  { route: "DELETE /api/agents/:id", bucket: "cat1", reason: "deleteAgents or creator; deleteAgent fenced; stop-before-delete effect open in #93" },
  { route: "DELETE /api/agents/:id/connections/:provider", bucket: "cat3", reason: "editAgents or creator, never guest; no Raft authority write (audit row only); the provider detaches the agent from its connector" },
  { route: "DELETE /api/agents/:id/connections/:provider/connectors/:connectorId", bucket: "cat3", reason: "editAgents or creator of the agent AND creator or owner/admin of the connector, never guest; no Raft authority write (audit row only); the provider disconnects the tenant connector" },
  { route: "DELETE /api/agents/:id/credentials/:credentialId", bucket: "pure", reason: "issueAgentCredentials or creator; agent credential revoke" },
  { route: "DELETE /api/attachments/^\\/upload-sessions\\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\\/?$/i", bucket: "notAgentMachine", reason: "attachments / share artifacts" },
  { route: "DELETE /api/auth/identities/:provider", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "DELETE /api/channels/:id", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "DELETE /api/channels/:id/members/agent/:memberId", bucket: "channelLane", reason: "channel removeChannelMembers capability under withLockedChannelActorCapability (DM participant for DMs); out of scope: channel authority lane (lib/channelActorPermissions.ts, Guest RBAC foundation); channel capability, not Server membership or Agent relationship authority" },
  { route: "DELETE /api/channels/:id/members/user/:memberId", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "DELETE /api/channels/saved/:messageId", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "DELETE /api/channels/threads/:threadChannelId/followers/agents/:agentId", bucket: "channelLane", reason: "thread author or channel manager; thread follower state; out of scope: channel authority lane (lib/channelActorPermissions.ts, Guest RBAC foundation); channel capability, not Server membership or Agent relationship authority" },
  { route: "DELETE /api/integrations/clients/:clientId", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "DELETE /api/integrations/clients/:clientId/app-notifications/webhook", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "DELETE /api/integrations/clients/:clientId/logo", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "DELETE /api/integrations/clients/:clientId/share-link", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "DELETE /api/integrations/marketplace/:clientId/install", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "DELETE /api/mcp/servers/:mcpServerId", bucket: "notAgentMachine", reason: "manageIntegrations capability; Server-level MCP server config" },
  { route: "DELETE /api/mcp/servers/:mcpServerId/oauth", bucket: "integrationLane", reason: "Managed MCP OAuth disconnect: confirmed removal/demotion race, fix #proj-backend-general task #165, audit task #164. Predicate: server capability manageExternalAuth (owner/admin); no Agent-relation authority" },
  { route: "DELETE /api/messages/:messageId/reactions", bucket: "notAgentMachine", reason: "message content" },
  { route: "DELETE /api/notifications/credentials/current", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "DELETE /api/notifications/devices/:deviceId", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "DELETE /api/provider-connections/:connectionId", bucket: "providerConnectionResidual", reason: "confirmed removal/demotion race, fix #proj-backend-general task #165 (unified, owner Ark), audit #167. Predicate: server capability manageExternalAuth; provider connection config, no Agent-relation authority" },
  { route: "DELETE /api/provider-connections/:connectionId/agents/:agentId", bucket: "providerConnectionResidual", reason: "confirmed removal/demotion race, fix #proj-backend-general task #165 (unified, owner Ark), audit #167. Predicate: server capability manageExternalAuth; detaches a deleted Agent's assignment, no Agent-relation authority" },
  { route: "DELETE /api/push/registrations/:installationId", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "DELETE /api/push/subscribe", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "DELETE /api/servers/:id", bucket: "notAgentMachine", reason: "owner soft-deletes the Server; no Agent/Machine/Computer rows written" },
  { route: "DELETE /api/servers/:id/invites/:inviteId", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "DELETE /api/servers/:id/join-links/:linkId", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "DELETE /api/servers/:id/machines/:machineId", bucket: "cat1", reason: "editMachines or registrant; deleteMachine fenced; Computer disconnect effect open in #93" },
  { route: "DELETE /api/servers/:id/machines/:machineId/workspaces/:directoryName", bucket: "cat3", reason: "orchestrator workspace delete only; #93 runtime command chain" },
  { route: "DELETE /api/servers/:id/members/:memberId", bucket: "authorityTransition", reason: "member removal: the DELETE on server_members that fenced writes linearize against" },
  { route: "DELETE /api/slack-bridge/provisioning/channel-pairs", bucket: "notAgentMachine", reason: "Slack bridge configuration / ingress" },
  { route: "DELETE /api/tasks/:taskId", bucket: "notAgentMachine", reason: "task board state" },
  { route: "DELETE /internal/agent-api/attachment-upload-sessions/:uploadId", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "DELETE /internal/agent-api/channels/:channelId/members", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "DELETE /internal/agent-api/messages/:msgId/reactions", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "DELETE /internal/agent-api/push-webhook", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "DELETE /internal/agent-api/reminders/:reminderId", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "DELETE /internal/agent/:id/channels/:channelId/members", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "DELETE /internal/agent/:id/messages/:messageId/reactions", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "DELETE /internal/agent/:id/reminders/:reminderId", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "DELETE /internal/computer/runners/:agentId/credentials/:credentialId", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "PATCH /api/agents/:id", bucket: "cat1", reason: "editAgents/creator + role; role change and updateAgent fenced; resetAgent effect open in #93" },
  { route: "PATCH /api/auth/me", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "PATCH /api/channels/:id", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "PATCH /api/channels/:id/members/:targetType/:memberId/role", bucket: "channelLane", reason: "changeChannelMemberRoles evaluated under channel + membership row locks; out of scope: channel authority lane (lib/channelActorPermissions.ts, Guest RBAC foundation); channel capability, not Server membership or Agent relationship authority" },
  { route: "PATCH /api/channels/:id/message-display-settings", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "PATCH /api/channels/:id/notification-settings", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "PATCH /api/integrations/clients/:clientId", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "PATCH /api/mcp/servers/:mcpServerId", bucket: "notAgentMachine", reason: "manageIntegrations capability; Server-level MCP server config" },
  { route: "PATCH /api/provider-connections/:connectionId", bucket: "providerConnectionResidual", reason: "confirmed removal/demotion race, fix #proj-backend-general task #165 (unified, owner Ark), audit #167. Predicate: server capability manageExternalAuth; provider connection config, no Agent-relation authority" },
  { route: "PATCH /api/servers/:id", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PATCH /api/servers/:id/labs/access", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PATCH /api/servers/:id/machines/:machineId", bucket: "pure", reason: "editMachines or registrant; machine row update" },
  { route: "PATCH /api/servers/:id/members/:memberId", bucket: "authorityTransition", reason: "role transition: the FOR UPDATE + UPDATE on server_members that fenced writes linearize against" },
  { route: "PATCH /api/servers/:id/notification-settings", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PATCH /api/servers/:id/onboarding-settings", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PATCH /api/servers/:id/public-guest-join", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PATCH /api/servers/:id/public-visibility", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PATCH /api/servers/:id/sidebar-order", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PATCH /api/servers/:id/product-analytics-settings", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PATCH /api/servers/:id/translation-settings", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PATCH /api/servers/order", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PATCH /api/tasks/:taskId/assignee", bucket: "notAgentMachine", reason: "assignTasks + channel write; task board state" },
  { route: "PATCH /api/tasks/:taskId/claim", bucket: "notAgentMachine", reason: "task board state" },
  { route: "PATCH /api/tasks/:taskId/status", bucket: "notAgentMachine", reason: "task board state" },
  { route: "PATCH /api/tasks/:taskId/unclaim", bucket: "notAgentMachine", reason: "task board state" },
  { route: "PATCH /internal/agent-api/apps/:appId/config", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "PATCH /internal/agent-api/channels/:channelId", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "PATCH /internal/agent-api/labs/access", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "PATCH /internal/agent-api/reminders/:reminderId", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "PATCH /internal/agent-api/server", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "PATCH /internal/agent/:id/channels/:channelId", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "PATCH /internal/agent/:id/reminders/:reminderId", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "PATCH /internal/agent/:id/server", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /^\\/api\\/message-translations:batch$/", bucket: "notAgentMachine", reason: "message content" },
  { route: "POST /api/actions/:messageId/event", bucket: "notAgentMachine", reason: "action card client telemetry event under channel read access" },
  { route: "POST /api/actions/:messageId/execute", bucket: "integrationLane", reason: "integration:approve_agent_login kind: confirmed race, fix #proj-backend-general task #165 (audit #164), predicate manageExternalAuth. install / register / recover integration kinds: confirmed unlocked in-transaction membership races, fix #proj-backend-general task #168, audit #167. agent:create / channel:add_member need a dialog and write nothing" },
  { route: "POST /api/actions/:messageId/mark-executed", bucket: "notAgentMachine", reason: "records card state; the create itself is POST /api/agents (line G)" },
  { route: "POST /api/actions/:messageId/reconfirm", bucket: "notAgentMachine", reason: "action card confirmation under card and channel write checks" },
  { route: "POST /api/actions/migration-export", bucket: "notAgentMachine", reason: "always 410; no write" },
  { route: "POST /api/agent/login", bucket: "nonHuman", reason: "bootstrap-token exchange (env-gated); caller holds no human session" },
  { route: "POST /api/agents", bucket: "lineG", reason: "createAgents capability only, no creator relation yet; removal/demotion race is #93 line G" },
  { route: "POST /api/agents/:id/assign-machine", bucket: "cat1", reason: "editAgents or creator; assignMachine fenced; runtime effect open in #93" },
  { route: "POST /api/agents/:id/connections/:provider", bucket: "cat3", reason: "editAgents or creator, never guest; no Raft authority write (audit row only); starts the provider-owned OAuth flow bound to the caller" },
  { route: "POST /api/agents/:id/connections/:provider/confirm", bucket: "cat3", reason: "editAgents or creator re-checked at confirm, never guest; no Raft authority write (audit row only); provider attaches only for the session user who initiated" },
  { route: "POST /api/agents/:id/hosted-runtime/retry", bucket: "pure", reason: "editAgents or creator; provisioning-row requeue fenced; provider call runs later in the provisioning worker" },
  { route: "POST /api/agents/:id/avatar", bucket: "cat1", reason: "editAgents or creator; avatar row write fenced; cache/runtime effect open in #93" },
  { route: "POST /api/agents/:id/bootstrap-tokens", bucket: "pure", reason: "issueAgentCredentials or creator; bootstrap token mint" },
  { route: "POST /api/agents/:id/credentials", bucket: "pure", reason: "issueAgentCredentials or creator; agent credential mint" },
  { route: "POST /api/agents/:id/migrate", bucket: "cat2", reason: "migration admission and effect both not linearized; #93 line C" },
  { route: "POST /api/agents/:id/migration/cancel", bucket: "cat2", reason: "migration cancellation admission and effect both not linearized; #93 line C" },
  { route: "POST /api/agents/:id/onboarding-identity-adoption", bucket: "pure", reason: "editAgents or creator; official onboarding identity adoption write" },
  { route: "POST /api/agents/:id/reset", bucket: "cat3", reason: "controlAgentRuntime or creator; orchestrator reset only; #93 runtime command chain" },
  { route: "POST /api/agents/:id/start", bucket: "cat2", reason: "auto-start migration completion admission and effect not linearized; #93 line C" },
  { route: "POST /api/agents/:id/stop", bucket: "cat3", reason: "controlAgentRuntime or creator; orchestrator stop only; #93 runtime command chain" },
  { route: "POST /api/announcements/:id/dismiss", bucket: "notAgentMachine", reason: "product announcements / release notes" },
  { route: "POST /api/app-installation/agent-reminder-messages", bucket: "nonHuman", reason: "App installation credential (official app with agent_reminder_write); no human session, no Agent/Machine relationship authority" },
  { route: "POST /api/attachments/:id/comments", bucket: "notAgentMachine", reason: "attachments / share artifacts" },
  { route: "POST /api/attachments/^\\/upload-sessions\\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\\/complete\\/?$/i", bucket: "notAgentMachine", reason: "attachments / share artifacts" },
  { route: "POST /api/attachments/upload", bucket: "notAgentMachine", reason: "attachments / share artifacts" },
  { route: "POST /api/attachments/upload-sessions", bucket: "notAgentMachine", reason: "attachments / share artifacts" },
  { route: "POST /api/attachments/urls", bucket: "notAgentMachine", reason: "attachments / share artifacts" },
  { route: "POST /api/auth/:provider/callback", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/:provider/complete", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/:provider/link/start", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/accept-invite", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/app-login/complete", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/app-login/requests/:id/approve", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/app-login/requests/:id/deny", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/app-login/start", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/device/approve", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/device/authorize", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/device/token", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/forgot-password", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/login", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/logout", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/me/avatar", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/me/complete-profile", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/me/timezone-observation", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/mobile/oauth/:provider/link/complete", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/mobile/oauth/:provider/link/start", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/mobile/oauth/apple/native/authorize", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/mobile/oauth/apple/native/start", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/mobile/oauth/complete", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/mobile/oauth/start", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/refresh", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/register", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/resend-verification", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/reset-password", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/staging-self-account/retire", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/auth/verify-email", bucket: "notAgentMachine", reason: "caller's own account, session or device login" },
  { route: "POST /api/billing/cancel", bucket: "notAgentMachine", reason: "Server billing" },
  { route: "POST /api/billing/checkout", bucket: "notAgentMachine", reason: "Server billing" },
  { route: "POST /api/billing/pack-quantity", bucket: "notAgentMachine", reason: "Server billing" },
  { route: "POST /api/billing/pack-quantity/preview", bucket: "notAgentMachine", reason: "Server billing" },
  { route: "POST /api/billing/portal", bucket: "notAgentMachine", reason: "Server billing" },
  { route: "POST /api/billing/seat-pack-quantity", bucket: "notAgentMachine", reason: "Server billing" },
  { route: "POST /api/billing/seat-pack-quantity/preview", bucket: "notAgentMachine", reason: "Server billing" },
  { route: "POST /api/channels", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/:id/archive", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/:id/convert-to-joint", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/:id/disconnect", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/:id/join", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/:id/joint-invite/resend", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/:id/joint-invites", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/:id/leave", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/:id/members", bucket: "channelLane", reason: "addChannelMembers channel capability (locked for non-DM); out of scope: channel authority lane (lib/channelActorPermissions.ts, Guest RBAC foundation); channel capability, not Server membership or Agent relationship authority" },
  { route: "POST /api/channels/:id/members/batch", bucket: "channelLane", reason: "addChannelMembers channel capability (locked for non-DM); out of scope: channel authority lane (lib/channelActorPermissions.ts, Guest RBAC foundation); channel capability, not Server membership or Agent relationship authority" },
  { route: "POST /api/channels/:id/read", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/:id/read-all", bucket: "readState93", reason: "human acting on an Agent's read state; admission and effect open in #93 line B" },
  { route: "POST /api/channels/:id/resume-all-agents", bucket: "cat3", reason: "controlAgentRuntime; orchestrator start per channel Agent only; #93 runtime command chain" },
  { route: "POST /api/channels/:id/stop-all-agents", bucket: "cat3", reason: "controlAgentRuntime; orchestrator stop per channel Agent only; #93 runtime command chain" },
  { route: "POST /api/channels/:id/threads", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/:id/unarchive", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/:id/unread", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/conversion-jobs/:jobId/cancel", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/conversion-jobs/:jobId/retry", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/dm", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/inbox/done", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/inbox/read-all", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/inbox/undone", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/joint-invites/:inviteId/accept", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/saved", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/saved/check", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/system/all/hide", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/system/all/restore", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/threads/:threadChannelId/followers/agents/:agentId/restore", bucket: "channelLane", reason: "thread author or channel manager; thread follower state; out of scope: channel authority lane (lib/channelActorPermissions.ts, Guest RBAC foundation); channel capability, not Server membership or Agent relationship authority" },
  { route: "POST /api/channels/threads/done", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/threads/follow", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/threads/undone", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/channels/threads/unfollow", bucket: "notAgentMachine", reason: "channel / thread / inbox state" },
  { route: "POST /api/computer/adopt-legacy", bucket: "cat1", reason: "registrant or registerMachines; adoption writes fenced; connection fencing effect open in #93" },
  { route: "POST /api/computer/attach", bucket: "lineG", reason: "registerMachines capability only; removal/demotion race is #93 line G" },
  { route: "POST /api/email/mobile-app/unsubscribe", bucket: "notAgentMachine", reason: "email unsubscribe" },
  { route: "POST /api/feature-flags/evaluate", bucket: "notAgentMachine", reason: "feature flag evaluation" },
  { route: "POST /api/integration-invites/:token/install", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: caller owns or administers the install target Server (installOAuthClientShareInvite); no Agent-relation authority" },
  { route: "POST /api/integrations/clients", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "POST /api/integrations/clients/:clientId/app-notifications/permissions/review", bucket: "integrationLane", reason: "membership race not applicable (audit #167). Predicate: isMarketplaceReviewer(userId), a Raft marketplace reviewer check, not Server membership authority" },
  { route: "POST /api/integrations/clients/:clientId/app-notifications/webhook/rotate-secret", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability rotateServerSecrets; no Agent-relation authority" },
  { route: "POST /api/integrations/clients/:clientId/logo", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "POST /api/integrations/clients/:clientId/regenerate-secret", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability rotateServerSecrets; no Agent-relation authority" },
  { route: "POST /api/integrations/clients/:clientId/request-publish", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "POST /api/integrations/clients/:clientId/request-unpublish", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "POST /api/integrations/clients/:clientId/review-publish", bucket: "integrationLane", reason: "membership race not applicable (audit #167). Predicate: isMarketplaceReviewer(userId), a Raft marketplace reviewer check, not Server membership authority" },
  { route: "POST /api/integrations/clients/:clientId/share-link", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "POST /api/integrations/agents/:agentId/grants", bucket: "integrationLane", reason: "Grant an app access to an agent on its behalf. Predicate: server capability manageExternalAuth, or the agent's human creator (fresh role read, member required); app must already be usable on the server" },
  { route: "POST /api/integrations/grants/:grantId/revoke", bucket: "integrationLane", reason: "confirmed removal/demotion race, fix #proj-backend-general task #165, audit #164. Predicate: server capability manageExternalAuth, or the human creator of the agent the request/grant is about (fresh role read, member required)" },
  { route: "POST /api/integrations/marketplace/:clientId/install", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "POST /api/integrations/requests/:requestId/approve", bucket: "integrationLane", reason: "confirmed removal/demotion race, fix #proj-backend-general task #165, audit #164. Predicate: server capability manageExternalAuth, or the human creator of the agent the request/grant is about (fresh role read, member required)" },
  { route: "POST /api/integrations/requests/:requestId/deny", bucket: "integrationLane", reason: "confirmed removal/demotion race, fix #proj-backend-general task #165, audit #164. Predicate: server capability manageExternalAuth, or the human creator of the agent the request/grant is about (fresh role read, member required)" },
  { route: "POST /api/mcp/servers", bucket: "notAgentMachine", reason: "manageIntegrations capability; Server-level MCP server config, no Agent/Machine relationship" },
  { route: "POST /api/mcp/servers/:mcpServerId/oauth/start", bucket: "integrationLane", reason: "Managed MCP OAuth start: confirmed removal/demotion race, fix #proj-backend-general task #165, audit task #164. Predicate: server capability manageExternalAuth (owner/admin); no Agent-relation authority" },
  { route: "POST /api/mcp/servers/:mcpServerId/test", bucket: "notAgentMachine", reason: "manageIntegrations capability; connectivity test, writes no Agent/Machine rows" },
  { route: "POST /api/mcp/servers/test-configuration", bucket: "notAgentMachine", reason: "manageIntegrations capability; configuration probe, writes no Agent/Machine rows" },
  { route: "POST /api/messages", bucket: "notAgentMachine", reason: "message content" },
  { route: "POST /api/messages/:messageId/reactions", bucket: "notAgentMachine", reason: "message content" },
  { route: "POST /api/messages/forward", bucket: "notAgentMachine", reason: "message content" },
  { route: "POST /api/messages/mention-actions/execute", bucket: "channelLane", reason: "addChannelMembers under channel row FOR UPDATE; message delivery only; out of scope: channel authority lane (lib/channelActorPermissions.ts, Guest RBAC foundation); channel capability, not Server membership or Agent relationship authority" },
  { route: "POST /api/notifications/credentials/rotate", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "POST /api/notifications/enrollment-exchanges", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "POST /api/notifications/enrollment-grants", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "POST /api/oauth/agent-events", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
  { route: "POST /api/oauth/authorize/human", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
  { route: "POST /api/oauth/installation-token", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
  { route: "POST /api/oauth/requests/agent", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
  { route: "POST /api/oauth/token", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
  { route: "POST /api/product-events/batch", bucket: "notAgentMachine", reason: "product telemetry / feedback" },
  { route: "POST /api/product-events/onboarding-wizard", bucket: "notAgentMachine", reason: "product telemetry / feedback" },
  { route: "POST /api/product-feedback", bucket: "notAgentMachine", reason: "product telemetry / feedback" },
  { route: "POST /api/product-feedback/tickets/:ticketId/close", bucket: "notAgentMachine", reason: "product telemetry / feedback" },
  { route: "POST /api/product-feedback/tickets/:ticketId/comments", bucket: "notAgentMachine", reason: "product telemetry / feedback" },
  { route: "POST /api/provider-connections", bucket: "providerConnectionResidual", reason: "confirmed removal/demotion race, fix #proj-backend-general task #165 (unified, owner Ark), audit #167. Predicate: server capability manageExternalAuth; provider connection config, no Agent-relation authority" },
  { route: "POST /api/provider-connections/:connectionId/credentials/rotate", bucket: "providerConnectionResidual", reason: "listed separately under rotateServerSecrets: removal/demotion race, fix #proj-backend-general task #165 (unified), audit task #167, owner Ark; no Agent-relation authority" },
  { route: "POST /api/provider-connections/:connectionId/probes", bucket: "providerConnectionResidual", reason: "confirmed removal/demotion race, fix #proj-backend-general task #165 (unified, owner Ark), audit #167. Predicate: server capability manageExternalAuth; provider connection config, no Agent-relation authority; the probe dispatch's final effect is a task #93 line A residual" },
  { route: "POST /api/provider-connections/:connectionId/test", bucket: "providerConnectionResidual", reason: "confirmed removal/demotion race, fix #proj-backend-general task #165 (unified, owner Ark), audit #167. Predicate: server capability manageExternalAuth; provider connection config, no Agent-relation authority; the legacy test's final effect is a task #93 line A residual" },
  { route: "POST /api/public/servers/:slug/join-as-guest", bucket: "notAgentMachine", reason: "public guest join" },
  { route: "POST /api/push/family-revoke", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "POST /api/push/prompt-events", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "POST /api/push/registrations", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "POST /api/push/subscribe", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "POST /api/push/test", bucket: "notAgentMachine", reason: "caller's own push / notification device registration" },
  { route: "POST /api/read-mutations", bucket: "notAgentMachine", reason: "caller's own human read state only (principalKind defaults to human)" },
  { route: "POST /api/servers", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "POST /api/servers/:id/avatar", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "POST /api/servers/:id/invites", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "POST /api/servers/:id/join-links", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "POST /api/servers/:id/leave", bucket: "authorityTransition", reason: "self-removal: the DELETE on server_members that fenced writes linearize against" },
  { route: "POST /api/servers/:id/machines", bucket: "lineG", reason: "registerMachines capability only; removal/demotion race is #93 line G" },
  { route: "POST /api/servers/:id/machines/:machineId/agents/:agentId/diagnostic/mention-delivery/:messageId/redrive", bucket: "cat3", reason: "editAgents or creator; orchestrator redrive only; #93 runtime command chain" },
  { route: "POST /api/servers/:id/machines/:machineId/agents/:agentId/feedback/:reportId/transcript", bucket: "cat3", reason: "editAgents or creator; daemon transcript request only; #93 runtime command chain" },
  { route: "POST /api/servers/:id/machines/:machineId/computer-lifecycle-operations", bucket: "cat1", reason: "controlComputers or registrant; operation/target admission fenced; dispatch effect open in #93" },
  { route: "POST /api/servers/:id/machines/:machineId/computer/:action", bucket: "cat1", reason: "controlComputers or registrant; operation/dispatch admission fenced; send effect open in #93" },
  { route: "POST /api/servers/:id/machines/:machineId/rotate-key", bucket: "pure", reason: "rotateMachineKeys or registrant; machine key rotation" },
  { route: "POST /api/servers/:id/machines/:machineId/runtime-account-usage/:provider/refresh", bucket: "cat3", reason: "attaching human or editMachines; cooldown cache key + runtime request; #93 runtime command chain" },
  { route: "POST /api/servers/:id/machines/:machineId/runtimes/rescan", bucket: "cat3", reason: "orchestrator runtime rescan only; #93 runtime command chain" },
  { route: "POST /api/servers/:id/scope-attestation", bucket: "notAgentMachine", reason: "signs a scope attestation; no DB write" },
  { route: "POST /api/servers/:id/setup-handoff", bucket: "notAgentMachine", reason: "owner acknowledges setup; best-effort onboarding message delivery, no Agent/Machine authority write" },
  { route: "POST /api/servers/:id/setup-reset", bucket: "cat1", reason: "servers.ownerId plus a live owner member row locked FOR UPDATE; Computer revocation fenced (confirmed steady-state gap: a removed primary owner could revoke Computers)" },
  { route: "POST /api/servers/:id/setup-transition", bucket: "notAgentMachine", reason: "owner's own setup-state row" },
  { route: "POST /api/servers/join-community", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "POST /api/share-artifacts/message-selection", bucket: "notAgentMachine", reason: "attachments / share artifacts" },
  { route: "POST /api/slack-bridge/events", bucket: "notAgentMachine", reason: "Slack bridge configuration / ingress" },
  { route: "POST /api/slack-bridge/oauth/start", bucket: "notAgentMachine", reason: "Slack bridge configuration / ingress" },
  { route: "POST /api/slack-bridge/provisioning/connect", bucket: "notAgentMachine", reason: "Slack bridge configuration / ingress" },
  { route: "POST /api/slack-bridge/provisioning/disconnect", bucket: "notAgentMachine", reason: "Slack bridge configuration / ingress" },
  { route: "POST /api/slack-bridge/provisioning/enable", bucket: "notAgentMachine", reason: "Slack bridge configuration / ingress" },
  { route: "POST /api/slack-bridge/provisioning/preflight", bucket: "notAgentMachine", reason: "Slack bridge configuration / ingress" },
  { route: "POST /api/tasks/channel/:channelId", bucket: "notAgentMachine", reason: "task board state" },
  { route: "POST /api/tasks/convert-message", bucket: "notAgentMachine", reason: "task board state" },
  { route: "POST /api/v2/messages", bucket: "notAgentMachine", reason: "message content" },
  { route: "POST /api/webhooks/resend", bucket: "nonHuman", reason: "third-party webhook ingress (signature-authenticated)" },
  { route: "POST /api/webhooks/stripe", bucket: "nonHuman", reason: "third-party webhook ingress (signature-authenticated)" },
  { route: "POST /api/workflows/:instanceId/complete-current-step", bucket: "notAgentMachine", reason: "workflow rows under channel write access" },
  { route: "POST /api/workflows/templates", bucket: "notAgentMachine", reason: "workflow rows under channel write access" },
  { route: "POST /api/workflows/templates/:templateId/start", bucket: "notAgentMachine", reason: "workflow rows under channel write access" },
  { route: "POST /internal/agent-api/activity", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/app-sources/ack", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/attachment-upload-sessions", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/attachment-upload-sessions/:uploadId/complete", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/attachments/:attachmentId/comments", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/channels", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/channels/:channelId/join", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/channels/:channelId/leave", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/channels/:channelId/members", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/channels/:channelId/mute", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/channels/:channelId/unmute", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/channels/archive", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/channels/unarchive", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/feedback-locators", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/integrations/app/logo", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/integrations/app/manage", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/integrations/app/prepare", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/integrations/app/rotate-secret", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/integrations/app/transfer-owner", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/integrations/app/update", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/integrations/login", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/integrations/token", bucket: "nonHuman", reason: "sk_agent principal; actor-bound audience JWT issuance rechecks Agent, App and grant authority" },
  { route: "POST /internal/agent-api/mcp/call", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/mention-actions/execute", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/messages/:msgId/reactions", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/prepare-action", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/profile", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/profile/avatar", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/reminders", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/reminders/:reminderId/snooze", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/resolve-channel", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/send", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/server/avatar", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/tasks", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/tasks/amend", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/tasks/assign", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/tasks/claim", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/tasks/convert", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/tasks/delete", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/tasks/resource-receipt", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/tasks/unclaim", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/tasks/update-status", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/third-party-events/delivered", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/threads/unfollow", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/upload", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent-api/v2/send", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/agent/:id/channels", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/channels/:channelId/join", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/channels/:channelId/leave", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/channels/:channelId/members", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/integrations/app/prepare", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/integrations/login", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/messages/:messageId/reactions", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/prepare-action", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/profile", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/profile/avatar", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/receive-ack", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/reminders", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/reminders/:reminderId/snooze", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/resolve-channel", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/runtime-profile/migration-done", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/send", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/server/avatar", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/tasks", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/tasks/claim", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/tasks/unclaim", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/tasks/update-status", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/threads/unfollow", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/agent/:id/upload", bucket: "nonHuman", reason: "legacy machine-key principal acting for its Agent; no human Server authority" },
  { route: "POST /internal/computer/agent-migrations/by-id/:migrationId/arrived", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/agent-migrations/by-id/:migrationId/flip-machine", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/agent-migrations/by-id/:migrationId/start-transfer", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/agent-migrations/by-id/:migrationId/cancel-ack", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/agent-migrations/by-id/:migrationId/resumable/stream-chunks/:chunkIndex", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/agent-migrations/by-id/:migrationId/resumable/chunks/:chunkIndex/receipt", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/agent-migrations/by-id/:migrationId/resumable/control", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/agent-migrations/by-id/:migrationId/resumable/source-quiesced", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/agent-migrations/by-id/:migrationId/resumable/source-progress", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/agent-migrations/by-id/:migrationId/resumable/upload-complete", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/agent-migrations/by-id/:migrationId/transport-lost", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/preflight", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/probes/:probeId/materialize", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/runners/:agentId/credentials", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/runners/:agentId/provider-connection", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/computer/runners/:agentId/stop", bucket: "nonHuman", reason: "Computer principal (routeAuthPolicy registry); no human Server authority" },
  { route: "POST /internal/machine/agents/:id/start", bucket: "nonHuman", reason: "legacy machine-key principal; no human Server authority" },
  { route: "POST /internal/machine/agents/:id/stop", bucket: "nonHuman", reason: "legacy machine-key principal; no human Server authority" },
  { route: "POST /internal/machine/scope-attestation", bucket: "nonHuman", reason: "legacy machine-key principal; no human Server authority" },
  { route: "POST /internal/trace-ingest/otlp/v1/traces", bucket: "nonHuman", reason: "trace ingest principal; no human Server authority" },
  { route: "POST /oidc/:server/api/oauth/agent-events", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
  { route: "POST /oidc/:server/api/oauth/authorize/human", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
  { route: "POST /oidc/:server/api/oauth/installation-token", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
  { route: "POST /oidc/:server/api/oauth/installations/lookup", bucket: "nonHuman", reason: "registered by the shared OAuth router but rejected by the OIDC scoped-mount allowlist" },
  { route: "POST /oidc/:server/api/oauth/requests/agent", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
  { route: "POST /oidc/:server/api/oauth/token", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
  { route: "PUT /api/agents/:id/connections/:provider", bucket: "cat3", reason: "editAgents or creator of the agent AND creator or owner/admin of the connector, never guest; no Raft authority write (audit row only); the provider points the agent's mount at the connector" },
  { route: "PUT /api/agents/:id/scopes", bucket: "pure", reason: "editAgents or creator; agent scope rows" },
  { route: "PUT /api/integrations/clients/:clientId/app-notifications/permissions", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "PUT /api/integrations/clients/:clientId/app-notifications/webhook", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "PUT /api/integrations/marketplace/:clientId/install/app-notifications/grant", bucket: "integrationLane", reason: "confirmed membership race, fix #proj-backend-general task #168 (owner Ark), audit #167. Predicate: server capability manageIntegrations; no Agent-relation authority" },
  { route: "PUT /api/mcp/agents/:agentId/assignments", bucket: "cat1", reason: "editAgents or creator; bulk managed MCP write fenced; resetAgent effect open in #93" },
  { route: "PUT /api/mcp/agents/:agentId/assignments/:mcpServerId", bucket: "pure", reason: "editAgents or creator; single managed MCP assignment upsert" },
  { route: "PUT /api/oauth/installations/:installationId/subscriptions", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
  { route: "POST /api/oauth/installations/lookup", bucket: "nonHuman", reason: "App client credentials resolve only that App's active installation on an exact Server" },
  { route: "PUT /api/servers/:id/agreement", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PUT /api/servers/:id/labs/:labKey", bucket: "notAgentMachine", reason: "Server settings, invites, join links, ordering" },
  { route: "PUT /api/slack-bridge/provisioning/channel-pairs", bucket: "notAgentMachine", reason: "Slack bridge configuration / ingress" },
  { route: "PUT /internal/agent-api/labs/:labKey", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "PUT /internal/agent-api/push-webhook", bucket: "nonHuman", reason: "sk_agent principal (routeAuthPolicy registry); no human Server authority" },
  { route: "PUT /oidc/:server/api/oauth/installations/:installationId/subscriptions", bucket: "nonHuman", reason: "OAuth protocol endpoint (client credentials, bearer token or integration consent); no Agent/Machine relationship authority" },
];

export function checkRouteClassification(
  registered: ReadonlyArray<{ method: string; path: string }>,
  table: readonly RouteClassification[] = ROUTE_AUTHORITY_CLASSIFICATION,
) {
  const registeredKeys = new Set(registered.map((route) => `${route.method} ${route.path}`));
  const seen = new Set<string>();
  const duplicates: string[] = [];
  for (const row of table) {
    if (seen.has(row.route)) duplicates.push(row.route);
    seen.add(row.route);
  }
  const pinnedCounts: Record<string, number> = {};
  for (const bucket of Object.keys(PINNED_BUCKET_COUNTS)) {
    pinnedCounts[bucket] = table.filter((row) => row.bucket === bucket).length;
  }
  return {
    unclassified: [...registeredKeys].filter((key) => !seen.has(key)).sort(),
    stale: [...seen].filter((key) => !registeredKeys.has(key)).sort(),
    duplicates,
    missingReasons: table.filter((row) => row.reason.trim() === "").map((row) => row.route),
    pinnedCounts,
  };
}
