-- RFC-061 inbox derivation chain — THE serving source for Activity/Inbox.
--
-- Provenance: SHOW CREATE MATERIALIZED VIEW from a deployed cluster (post
-- ordering fix: activity_at = COALESCE(latest_at, mention timestamp);
-- composite serving index (user_id, activity_at DESC)). This file is the
-- canonical repo record of the deployed chain; every deployed cluster carries
-- identical definitions. Apply order below follows dependencies.
--
-- Contract: RisingWave is a hard dependency. The server reads
-- rw_inbox_serving_v3 (RW_INBOX_SERVING_DERIVATION_VIEW) and
-- rw_activity_totals_v1 unconditionally; an unconfigured RisingWave or a read
-- failure throws (no fallback). The canonical inline Postgres SQL in
-- channelService.ts (search, guest access, authority transactions) mirrors the
-- same semantics — keep the two texts in lockstep (risingwaveNoFallback.test.ts
-- pins the selection model).
--
-- Prerequisites: the CDC source tables (rw_channels, rw_messages,
-- rw_channel_humans, rw_thread_follows, rw_user_channel_read_cursors_v2,
-- rw_message_mentions_v2, rw_inbox_target_mute_states_v2,
-- rw_user_channel_inbox_states, rw_inbox_suppression_states,
-- rw_joint_channel_servers, rw_joint_channels, rw_servers) are created by
-- the cluster bootstrap, not by this file (see infra/risingwave/sql/README.md).
--
-- Two CDC tables belong to this chain's own record (they were introduced for
-- it; the shared bootstrap provisions the rest):

CREATE TABLE rw_inbox_target_mute_states_v2 (receiver_type CHARACTER VARYING, receiver_id CHARACTER VARYING, server_id CHARACTER VARYING, source_channel_id CHARACTER VARYING, activity_muted BOOLEAN, mute_from_seq BIGINT, prefs_version INT, created_at timestamptz, updated_at timestamptz, PRIMARY KEY (receiver_type, receiver_id, source_channel_id)) FROM slock_neon_cdc TABLE 'public.inbox_target_mute_states';

CREATE INDEX idx_rw_inbox_target_mute_states_v2_receiver ON rw_inbox_target_mute_states_v2 (server_id, receiver_type, receiver_id);

CREATE TABLE rw_servers (id CHARACTER VARYING PRIMARY KEY, name CHARACTER VARYING, slug CHARACTER VARYING, owner_id CHARACTER VARYING, onboarding_agent_id CHARACTER VARYING, plan CHARACTER VARYING, plan_downgraded_at timestamptz, deleted_at timestamptz, created_at timestamptz, updated_at timestamptz) FROM slock_neon_cdc TABLE 'public.servers';

CREATE MATERIALIZED VIEW rw_message_channel_slim_v1 AS SELECT id, channel_id FROM public.rw_messages;

CREATE MATERIALIZED VIEW rw_message_preview_v1 AS SELECT id, seq, channel_id, LEFT(content, 200) AS preview, sender_type, sender_id, created_at, task_number, task_status, task_assignee_type, task_assignee_id FROM public.rw_messages;

CREATE MATERIALIZED VIEW rw_message_target_v2 AS WITH proj AS (SELECT s.local_channel_id, s.server_id, j.canonical_channel_id FROM public.rw_joint_channel_servers AS s JOIN public.rw_joint_channels AS j ON j.id = s.joint_channel_id WHERE s.status = 'active' AND j.status = 'active'), chan_map AS (SELECT c.id AS storage_id, c.id AS target_id FROM public.rw_channels AS c LEFT JOIN proj AS p ON p.local_channel_id = c.id WHERE c.deleted_at IS NULL AND c.archived_at IS NULL AND p.local_channel_id IS NULL UNION ALL SELECT p.canonical_channel_id AS storage_id, p.local_channel_id AS target_id FROM proj AS p) SELECT map.target_id, m.seq, m.created_at, m.sender_type, m.sender_id FROM public.rw_messages AS m JOIN chan_map AS map ON m.channel_id = map.storage_id;

CREATE MATERIALIZED VIEW rw_target_latest_v3 AS SELECT target_id, MAX(seq) AS latest_seq, MAX(created_at) AS latest_at, COUNT(*) AS msg_count FROM public.rw_message_target_v2 GROUP BY target_id;

CREATE MATERIALIZED VIEW rw_subs_v1 AS SELECT CASE WHEN c.type = 'dm' THEN 'dm' ELSE 'channel' END AS kind, ch.user_id, c.id AS target_id, c.server_id, st.done_at, ch.joined_at FROM public.rw_channel_humans AS ch JOIN public.rw_channels AS c ON ch.channel_id = c.id AND c.type <> 'thread' AND c.deleted_at IS NULL AND c.archived_at IS NULL LEFT JOIN public.rw_inbox_target_mute_states_v2 AS mu ON mu.receiver_type = 'user' AND mu.receiver_id = ch.user_id AND mu.source_channel_id = c.id AND mu.activity_muted LEFT JOIN public.rw_user_channel_inbox_states AS st ON st.user_id = ch.user_id AND st.channel_id = c.id WHERE mu.receiver_id IS NULL UNION ALL SELECT 'thread', tf.follower_id, c.id, c.server_id, tf.done_at, CAST(NULL AS timestamptz) FROM public.rw_thread_follows AS tf JOIN public.rw_channels AS c ON tf.thread_channel_id = c.id AND c.deleted_at IS NULL AND c.archived_at IS NULL WHERE tf.follower_type = 'user' AND tf.unfollowed_at IS NULL;

CREATE MATERIALIZED VIEW rw_thread_parent_v3 AS WITH proj AS (SELECT s.local_channel_id, s.server_id, j.canonical_channel_id FROM public.rw_joint_channel_servers AS s JOIN public.rw_joint_channels AS j ON j.id = s.joint_channel_id WHERE s.status = 'active' AND j.status = 'active') SELECT c.id AS thread_channel_id, c.parent_message_id, m.channel_id AS parent_channel_id, pc.name AS parent_channel_name, pc.type AS parent_channel_type FROM public.rw_channels AS c JOIN public.rw_message_channel_slim_v1 AS m ON m.id = c.parent_message_id JOIN public.rw_channels AS pc ON pc.id = m.channel_id LEFT JOIN proj AS px ON px.local_channel_id = c.id WHERE c.type = 'thread' AND px.local_channel_id IS NULL UNION ALL SELECT lt.id AS thread_channel_id, ct.parent_message_id, COALESCE(pl.local_channel_id, m.channel_id) AS parent_channel_id, pc2.name AS parent_channel_name, pc2.type AS parent_channel_type FROM public.rw_channels AS lt JOIN proj AS p ON p.local_channel_id = lt.id JOIN public.rw_channels AS ct ON ct.id = p.canonical_channel_id JOIN public.rw_message_channel_slim_v1 AS m ON m.id = ct.parent_message_id LEFT JOIN proj AS pl ON pl.canonical_channel_id = m.channel_id AND pl.server_id = lt.server_id JOIN public.rw_channels AS pc2 ON pc2.id = COALESCE(pl.local_channel_id, m.channel_id) WHERE lt.type = 'thread';

CREATE MATERIALIZED VIEW rw_inbox_normal_v3 AS SELECT s.kind, s.user_id, s.target_id, s.server_id, s.done_at, s.joined_at, COALESCE(rc.last_read_seq, 0) AS last_read, MAX(m.seq) AS latest_seq, MAX(m.created_at) AS latest_at, COUNT(*) FILTER (WHERE m.seq > COALESCE(rc.last_read_seq, 0) AND NOT (m.sender_type = 'user' AND m.sender_id = s.user_id)) AS unread_count, MIN(m.seq) FILTER (WHERE m.seq > COALESCE(rc.last_read_seq, 0) AND NOT (m.sender_type = 'user' AND m.sender_id = s.user_id)) AS first_unread_seq FROM public.rw_subs_v1 AS s LEFT JOIN public.rw_user_channel_read_cursors_v2 AS rc ON rc.user_id = s.user_id AND rc.channel_id = s.target_id LEFT JOIN public.rw_message_target_v2 AS m ON m.target_id = s.target_id GROUP BY s.kind, s.user_id, s.target_id, s.server_id, s.done_at, s.joined_at, rc.last_read_seq;

CREATE MATERIALIZED VIEW rw_inbox_mention_v4 AS WITH proj AS (SELECT s.local_channel_id, s.server_id, j.canonical_channel_id FROM public.rw_joint_channel_servers AS s JOIN public.rw_joint_channels AS j ON j.id = s.joint_channel_id WHERE s.status = 'active' AND j.status = 'active'), chan_map AS (SELECT c.id AS storage_id, c.id AS target_id FROM public.rw_channels AS c LEFT JOIN proj AS p ON p.local_channel_id = c.id WHERE c.deleted_at IS NULL AND c.archived_at IS NULL AND p.local_channel_id IS NULL UNION ALL SELECT p.canonical_channel_id AS storage_id, p.local_channel_id AS target_id FROM proj AS p) SELECT CASE WHEN c.type = 'thread' THEN 'thread' WHEN c.type = 'dm' THEN 'dm' ELSE 'channel' END AS kind, mm.target_id AS user_id, map.target_id AS target_id, c.server_id, COUNT(*) FILTER (WHERE mm.message_seq > COALESCE(rc.last_read_seq, 0)) AS mention_unread, MAX(mm.message_seq) FILTER (WHERE mm.message_seq > COALESCE(rc.last_read_seq, 0)) AS max_mention_seq, COUNT(*) AS total_mentions FROM public.rw_message_mentions_v2 AS mm JOIN chan_map AS map ON map.storage_id = mm.channel_id JOIN public.rw_channels AS c ON c.id = map.target_id AND c.deleted_at IS NULL AND c.archived_at IS NULL LEFT JOIN public.rw_channel_humans AS vis ON vis.channel_id = map.target_id AND vis.user_id = mm.target_id LEFT JOIN public.rw_thread_parent_v3 AS tp ON tp.thread_channel_id = map.target_id LEFT JOIN public.rw_channel_humans AS pvis ON pvis.channel_id = tp.parent_channel_id AND pvis.user_id = mm.target_id LEFT JOIN public.rw_thread_follows AS mf ON mf.thread_channel_id = map.target_id AND mf.follower_type = 'user' AND mf.follower_id = mm.target_id AND mf.unfollowed_at IS NULL LEFT JOIN public.rw_user_channel_read_cursors_v2 AS rc ON rc.user_id = mm.target_id AND rc.channel_id = map.target_id WHERE mm.target_type = 'user' AND ((c.type <> 'thread' AND vis.user_id IS NOT NULL) OR (c.type = 'thread' AND (pvis.user_id IS NOT NULL OR mf.follower_id IS NOT NULL)) OR mm.notified_at IS NOT NULL) GROUP BY 1, 2, 3, 4;

CREATE MATERIALIZED VIEW rw_activity_watermark_v3 AS WITH structural AS (SELECT ch.user_id, c.id AS target_id FROM public.rw_channel_humans AS ch JOIN public.rw_channels AS c ON ch.channel_id = c.id AND c.type <> 'thread' AND c.deleted_at IS NULL AND c.archived_at IS NULL UNION ALL SELECT tf.follower_id, c.id FROM public.rw_thread_follows AS tf JOIN public.rw_channels AS c ON tf.thread_channel_id = c.id AND c.deleted_at IS NULL AND c.archived_at IS NULL WHERE tf.follower_type = 'user' AND tf.unfollowed_at IS NULL), ranked AS (SELECT s.user_id, tl.latest_seq, ROW_NUMBER() OVER (PARTITION BY s.user_id ORDER BY tl.latest_seq DESC) AS rk FROM structural AS s JOIN public.rw_target_latest_v3 AS tl ON tl.target_id = s.target_id) SELECT user_id, MIN(latest_seq) AS watermark_seq FROM ranked WHERE rk <= 500 GROUP BY user_id;

CREATE MATERIALIZED VIEW rw_inbox_items_v7 AS WITH sup AS (SELECT receiver_id, target_kind, target_channel_id, MAX(done_through_seq) AS done_through_seq, MAX(done_at) AS sup_done_at FROM public.rw_inbox_suppression_states WHERE receiver_type = 'user' GROUP BY 1, 2, 3) SELECT COALESCE(n.kind, mn.kind) AS kind, COALESCE(n.user_id, mn.user_id) AS user_id, COALESCE(n.target_id, mn.target_id) AS target_id, COALESCE(n.server_id, mn.server_id) AS server_id, n.unread_count, n.first_unread_seq, n.latest_seq, n.latest_at, n.last_read AS last_read_seq, COALESCE(mn.mention_unread, 0) AS mention_unread, mn.max_mention_seq, COALESCE(mn.total_mentions, 0) AS total_mentions, ((n.user_id IS NOT NULL AND n.latest_seq IS NOT NULL AND (n.done_at IS NULL OR n.latest_at > n.done_at) AND (n.joined_at IS NULL OR n.latest_at > n.joined_at) AND (sn.receiver_id IS NULL OR (sn.done_through_seq IS NOT NULL AND n.latest_seq > sn.done_through_seq) OR (sn.done_through_seq IS NULL AND n.latest_at > sn.sup_done_at))) OR (COALESCE(mn.mention_unread, 0) > 0 AND n.user_id IS NULL AND (sm.receiver_id IS NULL OR (sm.done_through_seq IS NOT NULL AND mn.max_mention_seq > sm.done_through_seq)))) AS present FROM public.rw_inbox_normal_v3 AS n FULL JOIN public.rw_inbox_mention_v4 AS mn ON n.kind = mn.kind AND n.user_id = mn.user_id AND n.target_id = mn.target_id LEFT JOIN sup AS sn ON sn.receiver_id = n.user_id AND sn.target_channel_id = n.target_id AND sn.target_kind = CASE n.kind WHEN 'thread' THEN 'followed_thread' WHEN 'dm' THEN 'dm' ELSE 'channel' END LEFT JOIN sup AS sm ON sm.receiver_id = mn.user_id AND sm.target_channel_id = mn.target_id AND sm.target_kind = CASE mn.kind WHEN 'thread' THEN 'public_thread_mention' WHEN 'dm' THEN 'dm' ELSE 'public_channel_mention' END;

CREATE MATERIALIZED VIEW rw_inbox_serving_v3 AS SELECT p.server_id, p.user_id, p.kind, CASE WHEN p.kind = 'thread' THEN NULL ELSE p.target_id END AS channel_id, CASE WHEN p.kind = 'thread' THEN NULL ELSE c.name END AS channel_name, CASE WHEN p.kind = 'thread' THEN NULL ELSE c.type END AS channel_type, lm.id AS last_message_id, fu.id AS first_unread_message_id, CASE WHEN p.kind = 'thread' THEN NULL ELSE p.latest_at END AS last_message_at, CASE WHEN p.kind = 'thread' THEN NULL ELSE lm.preview END AS last_message_preview, CASE WHEN p.kind = 'thread' THEN NULL ELSE lm.sender_type END AS last_message_sender_type, CASE WHEN p.kind = 'thread' THEN NULL ELSE lm.sender_id END AS last_message_sender_id, CAST(COALESCE(p.unread_count, 0) AS INT) AS unread_count, CASE WHEN p.kind = 'thread' THEN p.target_id ELSE NULL END AS thread_channel_id, tp.parent_message_id, tp.parent_channel_id, tp.parent_channel_name, tp.parent_channel_type, pm.preview AS parent_message_preview, pm.sender_type AS parent_message_sender_type, pm.sender_id AS parent_message_sender_id, COALESCE(lm.preview, ma.preview) AS latest_activity_preview, COALESCE(lm.sender_type, ma.sender_type) AS latest_activity_sender_type, COALESCE(lm.sender_id, ma.sender_id) AS latest_activity_sender_id, COALESCE(lm.id, ma.id) AS latest_activity_message_id, p.latest_at AS last_activity_at, CASE WHEN p.kind = 'thread' THEN p.latest_at ELSE NULL END AS last_reply_at, CASE WHEN p.kind = 'thread' THEN CAST(tl.msg_count AS INT) ELSE NULL END AS reply_count, pm.task_number, pm.task_status, pm.task_assignee_type AS task_claimed_by_type, pm.task_assignee_id AS task_claimed_by_id, (p.mention_unread > 0) AS has_mention, (p.mention_unread > 0 AND p.unread_count IS NULL) AS mention_only, CAST(p.last_read_seq AS BIGINT) AS last_read_seq, COALESCE(p.latest_at, ma.created_at) AS activity_at, (p.total_mentions > 0) AS has_any_mention FROM public.rw_inbox_items_v7 AS p LEFT JOIN public.rw_activity_watermark_v3 AS w ON w.user_id = p.user_id LEFT JOIN public.rw_servers AS sv ON sv.id = p.server_id LEFT JOIN public.rw_channels AS c ON c.id = p.target_id LEFT JOIN public.rw_message_preview_v1 AS lm ON lm.seq = p.latest_seq LEFT JOIN public.rw_message_preview_v1 AS fu ON fu.seq = p.first_unread_seq LEFT JOIN public.rw_thread_parent_v3 AS tp ON tp.thread_channel_id = p.target_id AND p.kind = 'thread' LEFT JOIN public.rw_message_preview_v1 AS pm ON pm.id = tp.parent_message_id LEFT JOIN public.rw_target_latest_v3 AS tl ON tl.target_id = p.target_id LEFT JOIN public.rw_message_preview_v1 AS ma ON ma.seq = p.max_mention_seq WHERE p.present AND GREATEST(COALESCE(p.latest_seq, 0), COALESCE(p.max_mention_seq, 0)) >= COALESCE(w.watermark_seq, 0) AND (COALESCE(sv.plan, 'free') <> 'free' OR p.latest_at > NOW() - INTERVAL '30 days' OR (p.latest_at IS NULL AND p.mention_unread > 0));

CREATE MATERIALIZED VIEW rw_activity_totals_v1 AS SELECT i.user_id, i.server_id, CAST(COALESCE(SUM(CASE WHEN i.mention_only THEN 0 ELSE i.unread_count END), 0) AS INT) AS total_unread_count FROM public.rw_inbox_serving_v3 AS i WHERE (i.kind = 'thread' OR i.channel_type IN ('channel', 'private', 'joint', 'dm')) GROUP BY i.user_id, i.server_id;

CREATE INDEX idx_rw_inbox_serving_v3_user_activity ON rw_inbox_serving_v3(user_id, activity_at DESC);
